sudo: false
dist: trusty
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
- '9'
- '8'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
install:
- npm install -g lerna@2.10.1
- yarn run bootstrap
script:
- gulp /base::tsc

jobs:
  include:
    - stage: deploy
      node_js:
      - '9'
      script:
      - gulp /base::build
      deploy:
        provider: pages
        before_deploy: gulp /base::build
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: packages/base/styleguide
        on:
          branch: develop

#jobs:
#  include:
#  - stage: npm release
#    node_js: node
#    before_install:
#    - curl -o- -L https://yarnpkg.com/install.sh | bash
#    - git config --global user.email "travis@travis-ci.org"
#    - git config --global user.name "Travis CI"
#    - git status
#    install:
#    - npm install -g lerna@2.8.0
#    - yarn run bootstrap
#    before_script:
#    - npm config set //registry.npmjs.org/:_authToken ${NPM_AUTH_TOKEN}
#    script:
#    - lerna publish --conventional-commits --yes
#    branches:
#      only:
#      - master